#!/bin/sh
echo "You are going to install Aglare-FHD-PLI v5.1 ..."
status='/var/lib/opkg/status'
package='enigma2-plugin-skins-aglare-fhd-pli'

if grep -q $package $status; then
opkg remove $package > /dev/null 2>&1
fi

if [ -d /control ] ; then
rm -rf /control  > /dev/null 2>&1
fi
if [ -d /CONTROL ] ; then
rm -rf /CONTROL  > /dev/null 2>&1
fi
if [ -f /control ] ; then
rm -rf /control  > /dev/null 2>&1
fi
exit 0
